data:
  default_symbol: AAPL
  lookback_years: 3  # Reduced for faster processing
  train_ratio: 0.7
  validation_ratio: 0.15
  test_ratio: 0.15
  features:
    moving_averages: [5, 10, 20]  # Reduced for faster processing
    volatility_window: 20
    lag_periods: [1, 2, 3]  # Reduced for faster processing

models:
  arima:
    max_p: 3  # Reduced for faster convergence
    max_d: 2
    max_q: 3  # Reduced for faster convergence
    seasonal: false  # Disabled for faster training
    trend: 'c'
  lstm:
    sequence_length: 30  # Reduced for better performance with smaller datasets
    units: [32, 32]  # Smaller units for faster training
    dropout: 0.2
    epochs: 50  # Reduced for faster training
    batch_size: 16  # Smaller batch size
    early_stopping_patience: 5
  random_forest:
    n_estimators: 50  # Reduced for faster training
    max_depth: 8  # Reduced to prevent overfitting
    min_samples_split: 5
    min_samples_leaf: 2
    max_features: 'sqrt'
    random_state: 42

ensemble:
  weighting_method: inverse_error
  min_weight: 0.05  # Reduced to allow more flexibility
  confidence_level: 0.95
  dynamic_adjustment: true
  adjustment_window: 30